/* Snacks: real excerpts from famous open source projects (public domain or
   permissively licensed). Each entry carries its source and license in the
   header comment of the code itself. */
window.SNACKS = [
  {
    id: "sqlite",
    file: "util.c",
    lang: "C",
    icon: "c",
    repo: "sqlite/sqlite",
    license: "Public domain",
    code: "/* SQLite — src/util.c (public domain)\n * https://github.com/sqlite/sqlite/blob/master/src/util.c */\n\n/*\n** 2001 September 15\n**\n** The author disclaims copyright to this source code.  In place of\n** a legal notice, here is a blessing:\n**\n**    May you do good and not evil.\n**    May you find forgiveness for yourself and forgive others.\n**    May you share freely, never taking more than you give.\n**\n\n/*\n** If zNum represents an integer that will fit in 32-bits, then set\n** *pValue to that integer and return true.  Otherwise return false.\n**\n** This routine accepts both decimal and hexadecimal notation for integers.\n**\n** Any non-numeric characters that following zNum are ignored.\n** This is different from sqlite3Atoi64() which requires the\n** input number to be zero-terminated.\n*/\nint sqlite3GetInt32(const char *zNum, int *pValue){\n  sqlite_int64 v = 0;\n  int i, c;\n  int neg = 0;\n  if( zNum[0]=='-' ){\n    neg = 1;\n    zNum++;\n  }else if( zNum[0]=='+' ){\n    zNum++;\n  }\n#ifndef SQLITE_OMIT_HEX_INTEGER\n  else if( zNum[0]=='0'\n        && (zNum[1]=='x' || zNum[1]=='X')\n        && sqlite3Isxdigit(zNum[2])\n  ){\n    u32 u = 0;\n    zNum += 2;\n    while( zNum[0]=='0' ) zNum++;\n    for(i=0; i<8 && sqlite3Isxdigit(zNum[i]); i++){\n      u = u*16 + sqlite3HexToInt(zNum[i]);\n    }\n    if( (u&0x80000000)==0 && sqlite3Isxdigit(zNum[i])==0 ){\n      memcpy(pValue, &u, 4);\n      return 1;\n    }else{\n      return 0;\n    }\n  }\n#endif\n  if( !sqlite3Isdigit(zNum[0]) ) return 0;\n  while( zNum[0]=='0' ) zNum++;\n  for(i=0; i<11 && (c = zNum[i] - '0')>=0 && c<=9; i++){\n    v = v*10 + c;\n  }\n\n  /* The longest decimal representation of a 32 bit integer is 10 digits:\n  **\n  **             1234567890\n  **     2^31 -> 2147483648\n  */\n  testcase( i==10 );\n  if( i>10 ){\n    return 0;\n  }\n  testcase( v-neg==2147483647 );\n  if( v-neg>2147483647 ){\n    return 0;\n  }\n  if( neg ){\n    v = -v;\n  }\n  *pValue = (int)v;\n  return 1;\n}",
  },
  {
    id: "lua",
    file: "lstring.c",
    lang: "C",
    icon: "c",
    repo: "lua/lua",
    license: "MIT",
    code: "/* Lua — lstring.c (MIT license)\n * https://github.com/lua/lua/blob/master/lstring.c */\n\n** generic equality for strings\n*/\nint luaS_eqstr (TString *a, TString *b) {\n  size_t len1, len2;\n  const char *s1 = getlstr(a, len1);\n  const char *s2 = getlstr(b, len2);\n  return ((len1 == len2) &&  /* equal length and ... */\n          (memcmp(s1, s2, len1) == 0));  /* equal contents */\n}\n\n\nstatic unsigned luaS_hash (const char *str, size_t l, unsigned seed) {\n  unsigned int h = seed ^ cast_uint(l);\n  for (; l > 0; l--)\n    h ^= ((h<<5) + (h>>2) + cast_byte(str[l - 1]));\n  return h;\n}\n\n\nunsigned luaS_hashlongstr (TString *ts) {\n  lua_assert(ts->tt == LUA_VLNGSTR);\n  if (ts->extra == 0) {  /* no hash? */\n    size_t len = ts->u.lnglen;\n    ts->hash = luaS_hash(getlngstr(ts), len, ts->hash);\n    ts->extra = 1;  /* now it has its hash */\n  }\n  return ts->hash;",
  },
  {
    id: "redis",
    file: "sds.c",
    lang: "C",
    icon: "c",
    repo: "redis/redis",
    license: "BSD 3-clause",
    code: "/* Redis 7.2 — src/sds.c (BSD 3-clause)\n * https://github.com/redis/redis/blob/7.2.4/src/sds.c */\n\n/* Append the specified binary-safe string pointed by 't' of 'len' bytes to the\n * end of the specified sds string 's'.\n *\n * After the call, the passed sds string is no longer valid and all the\n * references must be substituted with the new pointer returned by the call. */\nsds sdscatlen(sds s, const void *t, size_t len) {\n    size_t curlen = sdslen(s);\n\n    s = sdsMakeRoomFor(s,len);\n    if (s == NULL) return NULL;\n    memcpy(s+curlen, t, len);\n    sdssetlen(s, curlen+len);\n    s[curlen+len] = '\\0';\n    return s;\n}\n\n/* Append the specified null terminated C string to the sds string 's'.\n *\n * After the call, the passed sds string is no longer valid and all the\n * references must be substituted with the new pointer returned by the call. */\nsds sdscat(sds s, const char *t) {\n    return sdscatlen(s, t, strlen(t));\n}",
  },
  {
    id: "curl",
    file: "escape.c",
    lang: "C",
    icon: "c",
    repo: "curl/curl",
    license: "curl license",
    code: "/* curl — lib/escape.c (curl license)\n * https://github.com/curl/curl/blob/master/lib/escape.c */\n\n/* Escapes for URL the given unescaped string of given length.\n * 'data' is ignored since 7.82.0.\n */\nchar *curl_easy_escape(CURL *curl, const char *string, int length)\n{\n  size_t len;\n  struct dynbuf d;\n  (void)curl;\n\n  if(!string || (length < 0))\n    return NULL;\n\n  len = (length ? (size_t)length : strlen(string));\n  if(!len)\n    return curlx_strdup(\"\");\n\n  if(len > SIZE_MAX / 16)\n    return NULL;\n\n  curlx_dyn_init(&d, (len * 3) + 1);\n\n  while(len--) {\n    /* treat the characters unsigned */\n    unsigned char in = (unsigned char)*string++;\n\n    if(ISUNRESERVED(in)) {\n      /* append this */\n      if(curlx_dyn_addn(&d, &in, 1))\n        return NULL;\n    }\n    else {\n      /* encode it */\n      unsigned char out[3] = { '%' };\n      Curl_hexbyte(&out[1], in);\n      if(curlx_dyn_addn(&d, out, 3))\n        return NULL;\n    }\n  }",
  },
  {
    id: "go",
    file: "once.go",
    lang: "Go",
    icon: "go",
    repo: "golang/go",
    license: "BSD 3-clause",
    code: "// Go — src/sync/once.go (BSD 3-clause), excerpt\n// https://github.com/golang/go/blob/master/src/sync/once.go\n\n// Copyright 2009 The Go Authors. All rights reserved.\n// Use of this source code is governed by a BSD-style\n// license that can be found in the LICENSE file.\n\npackage sync\n\nimport (\n\t\"sync/atomic\"\n)\n\ntype Once struct {\n\t_ noCopy\n\n\t// done indicates whether the action has been performed.\n\t// It is first in the struct because it is used in the hot path.\n\t// The hot path is inlined at every call site.\n\t// Placing done first allows more compact instructions on some architectures (amd64/386),\n\t// and fewer instructions (to calculate offset) on other architectures.\n\tdone atomic.Bool\n\tm    Mutex\n}\n\nfunc (o *Once) Do(f func()) {\n\tif !o.done.Load() {\n\t\to.doSlow(f)\n\t}\n}\n\nfunc (o *Once) doSlow(f func()) {\n\to.m.Lock()\n\tdefer o.m.Unlock()\n\tif !o.done.Load() {\n\t\tdefer o.done.Store(true)\n\t\tf()\n\t}\n}",
  },
  {
    id: "python",
    file: "heapq.py",
    lang: "Python",
    icon: "py",
    repo: "python/cpython",
    license: "PSF",
    code: "# CPython — Lib/heapq.py (PSF license)\n# https://github.com/python/cpython/blob/main/Lib/heapq.py\n\ndef heappush(heap, item):\n    \"\"\"Push item onto heap, maintaining the heap invariant.\"\"\"\n    heap.append(item)\n    _siftdown(heap, 0, len(heap)-1)\n\ndef heappop(heap):\n    \"\"\"Pop the smallest item off the heap, maintaining the heap invariant.\"\"\"\n    lastelt = heap.pop()    # raises appropriate IndexError if heap is empty\n    if heap:\n        returnitem = heap[0]\n        heap[0] = lastelt\n        _siftup(heap, 0)\n        return returnitem\n    return lastelt\n\n# 'heap' is a heap at all indices >= startpos, except possibly for pos.  pos\n# is the index of a leaf with a possibly out-of-order value.  Restore the\n# heap invariant.\ndef _siftdown(heap, startpos, pos):\n    newitem = heap[pos]\n    # Follow the path to the root, moving parents down until finding a place\n    # newitem fits.\n    while pos > startpos:\n        parentpos = (pos - 1) >> 1\n        parent = heap[parentpos]\n        if newitem < parent:\n            heap[pos] = parent\n            pos = parentpos\n            continue\n        break",
  },
  {
    id: "react",
    file: "shallowEqual.js",
    lang: "JavaScript",
    icon: "js",
    repo: "facebook/react",
    license: "MIT",
    code: "// React — packages/shared/shallowEqual.js (MIT license)\n// https://github.com/facebook/react/blob/main/packages/shared/shallowEqual.js\n\n/**\n * Copyright (c) Meta Platforms, Inc. and affiliates.\n *\n * This source code is licensed under the MIT license found in the\n * LICENSE file in the root directory of this source tree.\n *\n * @flow\n */\n\nimport is from './objectIs';\nimport hasOwnProperty from './hasOwnProperty';\n\n/**\n * Performs equality by iterating through keys on an object and returning false\n * when any key has values which are not strictly equal between the arguments.\n * Returns true when the values of all keys are strictly equal.\n */\nfunction shallowEqual(objA: mixed, objB: mixed): boolean {\n  if (is(objA, objB)) {\n    return true;\n  }\n\n  if (\n    typeof objA !== 'object' ||\n    objA === null ||\n    typeof objB !== 'object' ||\n    objB === null\n  ) {\n    return false;\n  }\n\n  const keysA = Object.keys(objA);\n  const keysB = Object.keys(objB);\n\n  if (keysA.length !== keysB.length) {\n    return false;\n  }\n\n  // Test for A's keys different from B.\n  for (let i = 0; i < keysA.length; i++) {\n    const currentKey = keysA[i];\n    if (\n      !hasOwnProperty.call(objB, currentKey) ||\n      // $FlowFixMe[incompatible-use] lost refinement of `objB`\n      !is(objA[currentKey], objB[currentKey])\n    ) {\n      return false;\n    }\n  }\n\n  return true;\n}\n\nexport default shallowEqual;",
  },
  {
    id: "rust",
    file: "once.rs",
    lang: "Rust",
    icon: "rs",
    repo: "rust-lang/rust",
    license: "MIT / Apache-2.0",
    code: "// Rust — library/core/src/cell/once.rs (MIT / Apache-2.0), excerpt\n// https://github.com/rust-lang/rust/blob/master/library/core/src/cell/once.rs\n\nimpl<T> OnceCell<T> {\n    #[inline]\n    #[stable(feature = \"once_cell\", since = \"1.70.0\")]\n    #[rustc_should_not_be_called_on_const_items]\n    pub fn get_or_init<F>(&self, f: F) -> &T\n    where\n        F: FnOnce() -> T,\n    {\n        match self.get_or_try_init(|| Ok::<T, !>(f())) {\n            Ok(val) => val,\n        }\n    }\n\n    // Avoid inlining the initialization closure into the common path that fetches\n    // the already initialized value\n    #[cold]\n    fn try_init<F, E>(&self, f: F) -> Result<&T, E>\n    where\n        F: FnOnce() -> Result<T, E>,\n    {\n        let val = f()?;\n        // Note that *some* forms of reentrant initialization might lead to\n        // UB (see `reentrant_init` test). I believe that just removing this\n        // `panic`, while keeping `try_insert` would be sound, but it seems\n        // better to panic, rather than to silently use an old value.\n        if let Ok(val) = self.try_insert(val) { Ok(val) } else { panic!(\"reentrant init\") }\n    }\n}",
  },
  {
    id: "own",
    file: "my-code.txt",
    lang: "Plain Text",
    icon: "txt",
    repo: "you",
    license: "yours",
    code: "",
  },
];
